### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by wyamout** [zach-adams/hgv-deploy-full#18]
~/hgv-deploy-full# sudo ansible-playbook -i hosts playbook.yml -c local

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 324, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/bin/ansible-playbook", line 157, in main
    inventory = ansible.inventory.Inventory(options.inventory, vault_password=va                                       ult_pass)
  File "/usr/lib/pymodules/python2.7/ansible/inventory/**init**.py", line 149, i                                       n **init**
    host.vars = utils.combine_vars(host.vars, self.get_host_variables(host.name,                                        vault_password=self._vault_password))
  File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 448, i                                       n get_host_variables
    self._vars_per_host[hostname] = self._get_host_variables(hostname, vault_pas                                       sword=vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 478, i                                       n _get_host_variables
    vars = utils.combine_vars(vars, self.get_host_vars(host))
  File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 601, i                                       n get_host_vars
    return self._get_hostgroup_vars(host=host, group=None, new_pb_basedir=new_pb                                       _basedir)
  File "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 650, i                                       n _get_hostgroup_vars
    results = utils.load_vars(base_path, results, vault_password=self._vault_pas                                       sword)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 1526, in l                                       oad_vars
    found, results = _load_vars_from_path(path, results, vault_password=vault_pa                                       ssword)
  File "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 1584, in _                                       load_vars_from_path
    data = parse_yaml_from_file(path, vault_password=vault_password)
  File "/usr/lib/pymodules/python2.7/ansible/utils/**init**.py", line 780, in pa                                       rse_yaml_from_file
    process_yaml_error(exc, data, path, show_content)
  File "/usr/lib/pymodules/python2.7/ansible/utils/**init**.py", line 706, in pr                                       ocess_yaml_error
    probline = data.split("\n")[mark.line]
IndexError: list index out of range

**Comment by dhilditch** [comment]
Which version of Ubuntu are you using and is it 32 bit or 64 bit?

On 13 May 2015 at 11:34, wyamout notifications@github.com wrote:

> ~/hgv-deploy-full# sudo ansible-playbook -i hosts playbook.yml -c local
> 
> Traceback (most recent call last):
> File "/usr/bin/ansible-playbook", line 324, in
> sys.exit(main(sys.argv[1:]))
> File "/usr/bin/ansible-playbook", line 157, in main
> inventory = ansible.inventory.Inventory(options.inventory,
> vault_password=va ult_pass)
> File "/usr/lib/pymodules/python2.7/ansible/inventory/_init_.py", line
> 149, i n _init_
> host.vars = utils.combine_vars(host.vars, self.get_host_variables(
> host.name, vault_password=self.
> _vault_password)) File
> "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 448, i
> n get_host_variables
> self.
> _vars_per_host[hostname] = self.get_host_variables(hostname, vault_pas
> sword=vault_password) File
> "/usr/lib/pymodules/python2.7/ansible/inventory/__init_.py", line 478, i
> n
> 
> _get_host_variables vars = utils.combine_vars(vars,
> self.get_host_vars(host)) File
> "/usr/lib/pymodules/python2.7/ansible/inventory/__init__.py", line 601, i
> n get_host_vars
> return self.
> _get_hostgroup_vars(host=host, group=None, new_pb_basedir=new_pb basedir)
> File "/usr/lib/pymodules/python2.7/ansible/inventory/__init_.py", line
> 650, i n
> 
> _get_hostgroup_vars results = utils.load_vars(base_path, results,
> vault_password=self.vault_pas sword) File
> "/usr/lib/pymodules/python2.7/ansible/utils/__init_.py", line 1526, in l
> oad_vars
> found, results =
> _load_vars_from_path(path, results, vault_password=vault_pa ssword) File
> "/usr/lib/pymodules/python2.7/ansible/utils/__init__.py", line 1584, in _
> load_vars_from_path
> data = parse_yaml_from_file(path, vault_password=vault_password)
> File "/usr/lib/pymodules/python2.7/ansible/utils/_init_.py", line 780, in
> pa rse_yaml_from_file
> process_yaml_error(exc, data, path, show_content)
> File "/usr/lib/pymodules/python2.7/ansible/utils/_init_.py", line 706, in
> pr ocess_yaml_error
> probline = data.split("\n")[mark.line]
> IndexError: list index out of range
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zach-adams/hgv-deploy-full/issues/18.

## 

_Dave Hilditch_
Founder
www.affiliatewebdesigners.com

Skype: davehilditch
Landline: +44 131 208 1118
Mobile/Cell: +44 7961 552 082
Twitter: @davehilditch https://twitter.com/davehilditch

**Comment by wyamout** [comment]
64...

wait i deleted the folder and recloned i think working now...
thanks
